name: Run all tests [Ubuntu]
on: [push, pull_request]

env:
    LLVM_VERSION: "15"
    LLVM_CONFIG: llvm-config-15

jobs:
    test:
        name: SDC Tests
        strategy:
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-beta] # We shoudl use latest, but it's broken, so in the meantime we use beta.

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout SDC
              uses: actions/checkout@v2
            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}
            - name: Print D version
              run: dmd --version
            - name: Install system dependencies
              run: sudo apt install nasm lld llvm-${{ env.LLVM_VERSION }}-dev
            - name: Print LLVM version
              run: ${{ env.LLVM_CONFIG }} --version
            # CI runners usually top out at 4 "cores", but things are often busy so -j6 is a happy medium.
            - name: Build
              run: make -j6
            - name: Test
              run: make -j6 check

    sdfmt:
        name: Build sdfmt via dub
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-latest, dmd-beta, ldc-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}
            - name: Build sdfmt
              run: dub build :sdfmt
