name: Run all tests [Ubuntu]
on: [push, pull_request]

jobs:
    test:
        name: SDC Tests (should be split up eventually)
        strategy:
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}
            - name: Print D version
              run: dmd --version
            - name: Install sdc deps
              run: sudo apt install llvm nasm lld
            - name: Print LLVM version
              run: llvm-config --version
            - name: Checkout SDC
              uses: actions/checkout@v2
            # CI runners usually top out at 4 "cores", but things are often busy so -j6 is a happy medium.
            - name: Build
              run: make -j6
            - name: Test
              run: make -j6 check

    sdfmt:
        name: Build sdfmt via dub
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-latest, ldc-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}
            - name: Build sdfmt
              run: dub build :sdfmt
